### ISSUE TITLE
Image to image.

### ISSUE THREAD

**Issue by FooleanBool** [ImDarkTom/ComfyUIMini#11]
It works well, thank you.
I'm new to image gen and comfyui so the workflows are a steep learning curve.

I've tried to setup an image to image workflow but I suspect there is no file chooser integration as of now.
Am I missing something obvious?
When I setup the input chooser, I can only see references to the model subfolder, but no reference to the input folder which was another option.

Thanks again, and best wishes.

**Comment by ImDarkTom** [comment]
Currently there is no way to use img2img workflows as there isn't a file select input, you didn't miss anything. 

I'm currently working on changing the way inputs work and am planning on adding image inputs soon after that.

**Comment by FooleanBool** [comment]
Thanks for the response.
Look forward to the updates.
Best wishes.

**Comment by ImDarkTom** [comment]
img2img has been fully implemented in the latest release.
