### ISSUE TITLE
reordered inputs aren't saved

### ISSUE THREAD

**Issue by dpm316** [ImDarkTom/ComfyUIMini#17]
to repro:
1. select workflow 
2. select edit 
3. use up/down icons to rearrange inputs
4. select save (tried text button and purple icon.. is there any difference?)
5. select workflow 

expected result:
input order should reflect changes made in step 3 above

actual result:
input order is unchanged

**Comment by Hujikuio** [comment]
experiencing this as well, except sometimes some inputs will change, some will outright be completely gone, and some will be in a random order.

**Comment by ImDarkTom** [comment]
Fix has been implemented in the latest release.

**Comment by dpm316** [comment]
@ImDarkTom Thanks for the fix, but it still isn't working. I tried editing an existing workflow and a newly imported workflow using the latest release. Neither case worked.

**Comment by ImDarkTom** [comment]
@dpm316 @axiopaladin Try the latest patch it should be fixed.

> Is there any difference between using the text button at the bottom of the edit window vs. the purple circle icon button?

Both the button at the bottom of the page and the main action button run the same function, so there shouldn't be a difference.

**Comment by axiopaladin** [comment]
Seems to work now! Though it seems to have introduced a new bug. If a node is marked as "hidden", it completely disappears from the menu if you try to edit the workflow again later... so, once you save it as hidden, you can't ever unhide it.
