### ISSUE TITLE
rgthree modules not visible in workflow editor

### ISSUE THREAD

**Issue by chezolver** [ImDarkTom/ComfyUIMini#19]
Hello,

The rgthree nodes such as the `Fast Groups Muter (rgthree)` isn't visible to select when editing a workflow.

https://github.com/rgthree/rgthree-comfy

Would it be possible to add support?

**Comment by ImDarkTom** [comment]
Unfortunately this is a problem with the rgthree extension itself, the 'Fast Groups Muter' node doesn't appear in ComfyUI's `/object_info`, so ComfyUIMini or other apps that rely on the ComfyUI API, won't be able to see it. 

I suggest you open an issue in their repo as I am unable to do anything until then.
