### ISSUE TITLE
Program crashes when a preview method is enabled

### ISSUE THREAD

**Issue by daveiator** [ImDarkTom/ComfyUIMini#3]
Hi,
first of all: What a great project! I'm glad to have found it.
However it didn't work for me on the first try and I had to do some troubleshooting.

Turns out that if you have a Preview Method enabled, non JSON messages are getting sent to the websocket which crashes the program.
When ComfyUIMini is the only interface, disabling the preview would be the smart option, but some people may want to use multiple UIs on different devices.
While a preview in your UI would be pretty nice, a quicker fix for this problem would be to simply ignore non JSON messages by checking the data right before the JSON parsing.

https://github.com/ImDarkTom/ComfyUIMini/blob/a150b4aee97e05d00dbdef52635153bfbbc289f6/src/utils/comfyUI.js#L93
 Or mentioning this info somewhere in the README.

Hope this helps.
Have a great day.

**Comment by ImDarkTom** [comment]
Generation previews have now been fully implemented in the latest release.
