### ISSUE TITLE
Error when adding first workflow

### ISSUE THREAD

**Issue by moebiussurfing** [ImDarkTom/ComfyUIMini#6]
Hello @ImDarkTom ,
I am getting the error when opening the web app. (after `node .`)

![image](https://github.com/user-attachments/assets/04bcb1a3-f100-4900-b64d-b7f56fefec2b)

BTW If the folder is empty the web app/UI opens well.
I am on Windows 11.

![image](https://github.com/user-attachments/assets/6cb0f9bf-b05e-486d-b35b-6f920af4c2ee)

Models dir json seems to be fine:

![image](https://github.com/user-attachments/assets/45f83bc0-866f-4b69-81f3-bcd6a43fe7b8)

**Comment by ImDarkTom** [comment]
Are you importing them through the UI or dropping the exported result directly into the folder?

**Comment by moebiussurfing** [comment]
> Are you importing them through the UI or dropping the exported result directly into the folder?

I am dropping the files directly using the windows explorer...

**Comment by ImDarkTom** [comment]
You need to import them through the import page, otherwise it will not be able to read it.

**Comment by moebiussurfing** [comment]
ok. Thanks. It worked! 
BTW I was required to tweak the Edge browser (~70%) to allow see the save button below the parameters lists.
